### ISSUE TITLE
[bug] integration-test error on barnard network

### ISSUE THREAD

**Issue by 0xpause** [starcoinorg/starcoin-framework-commons#13]
# Bug Report

**Starcoin network:**

barnard 

**Error location or Error stack trace:**

```
$ mpm integration-test
BUILDING StarcoinFramework
BUILDING starcoin-framework-commons

running 2 tests

test integration-test::test_sqrt_u256.move ... ok
thread 'integration-test::ascii_test.move' panicked at 'index out of bounds: the len is 20 but the index is 30', /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-core/types/src/gas_schedule.rs:251:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test integration-test::ascii_test.move ... FAILED

failures:
    integration-test::ascii_test.move

test result: FAILED. 1 passed; 1 failed; 0 filtered out
```

with `RUST_BACKTRACE=1` environment variable:
```
$ RUST_BACKTRACE=1 mpm integration-test
BUILDING StarcoinFramework
BUILDING starcoin-framework-commons

running 2 tests

test integration-test::test_sqrt_u256.move ... ok
thread 'integration-test::ascii_test.move' panicked at 'index out of bounds: the len is 20 but the index is 30', /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-core/types/src/gas_schedule.rs:251:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_bounds_check
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:85:5
   3: move_vm_types::natives::function::native_gas
   4: starcoin_natives::vector::native_append
   5: move_vm_runtime::interpreter::Interpreter::call_native
   6: move_vm_runtime::interpreter::Interpreter::execute_main
             at /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-vm/runtime/src/interpreter.rs:193:25
   7: move_vm_runtime::interpreter::Interpreter::execute
             at /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-vm/runtime/src/interpreter.rs:106:9
   8: move_vm_runtime::interpreter::Interpreter::entrypoint
             at /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-vm/runtime/src/interpreter.rs:82:9
   9: move_vm_runtime::runtime::VMRuntime::execute_function_impl
             at /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-vm/runtime/src/runtime.rs:497:13
  10: move_vm_runtime::runtime::VMRuntime::execute_script_function
             at /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-vm/runtime/src/runtime.rs:534:27
  11: move_vm_runtime::session::Session<S>::execute_script_function
             at /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-vm/runtime/src/session.rs:159:9
  12: starcoin_vm_runtime::starcoin_vm::StarcoinVM::execute_script_or_script_function
             at /home/runner/work/starcoin/starcoin/vm/vm-runtime/src/starcoin_vm.rs:586:21
  13: starcoin_vm_runtime::starcoin_vm::StarcoinVM::dry_run_transaction
             at /home/runner/work/starcoin/starcoin/vm/vm-runtime/src/starcoin_vm.rs:937:66
  14: starcoin_transactional_test_harness::StarcoinTestAdapter::run_transaction
  15: <starcoin_transactional_test_harness::StarcoinTestAdapter as move_transactional_test_runner::framework::MoveTestAdapter>::handle_subcommand
  16: move_transactional_test_runner::framework::MoveTestAdapter::handle_command
  17: move_transactional_test_runner::framework::run_test_impl
  18: core::ops::function::FnOnce::call_once
  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test integration-test::ascii_test.move ... FAILED

failures:
    integration-test::ascii_test.move

test result: FAILED. 1 passed; 1 failed; 0 filtered out
```

with `RUST_BACKTRACE=full` environment variable:
```
s$ RUST_BACKTRACE=full mpm integration-test
BUILDING StarcoinFramework
BUILDING starcoin-framework-commons

running 2 tests

test integration-test::test_sqrt_u256.move ... ok
thread 'integration-test::ascii_test.move' panicked at 'index out of bounds: the len is 20 but the index is 30', /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-core/types/src/gas_schedule.rs:251:10
stack backtrace:
   0:     0x7f5e840324fd - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f5e840324fd - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f5e840324fd - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f5e840324fd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f5e8405d81c - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x7f5e840296b8 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x7f5e84034987 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f5e84034987 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f5e84034987 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x7f5e84034650 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x7f5e840350d9 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x7f5e84034dc7 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:     0x7f5e840329c4 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x7f5e84034ad9 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:     0x7f5e82c3aef3 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:     0x7f5e82c3ae32 - core::panicking::panic_bounds_check::h7777e18766a27b0b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:85:5
  16:     0x7f5e8301600c - move_vm_types::natives::function::native_gas::ha82aee6a95ed309d
  17:     0x7f5e8301a037 - starcoin_natives::vector::native_append::h941da48a5e1e92b2
  18:     0x7f5e837461a4 - move_vm_runtime::interpreter::Interpreter::call_native::h61c3e3753c22e19e
  19:     0x7f5e82fc66a7 - move_vm_runtime::interpreter::Interpreter::execute_main::h872a027dc71e7c14
                               at /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-vm/runtime/src/interpreter.rs:193:25
  20:     0x7f5e82fc66a7 - move_vm_runtime::interpreter::Interpreter::execute::h56627f7c126fa29e
                               at /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-vm/runtime/src/interpreter.rs:106:9
  21:     0x7f5e82fc66a7 - move_vm_runtime::interpreter::Interpreter::entrypoint::hde3eeebc5cf78b27
                               at /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-vm/runtime/src/interpreter.rs:82:9
  22:     0x7f5e82ff8cac - move_vm_runtime::runtime::VMRuntime::execute_function_impl::hc250c49790e88187
                               at /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-vm/runtime/src/runtime.rs:497:13
  23:     0x7f5e82ff8cac - move_vm_runtime::runtime::VMRuntime::execute_script_function::h84bc3e662faa6960
                               at /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-vm/runtime/src/runtime.rs:534:27
  24:     0x7f5e82ff8cac - move_vm_runtime::session::Session<S>::execute_script_function::h81acc101b45e08b7
                               at /home/runner/.cargo/git/checkouts/move-ae0d26a86327ae96/8d559a8/language/move-vm/runtime/src/session.rs:159:9
  25:     0x7f5e82fd8a73 - starcoin_vm_runtime::starcoin_vm::StarcoinVM::execute_script_or_script_function::ha3dd67efda64af60
                               at /home/runner/work/starcoin/starcoin/vm/vm-runtime/src/starcoin_vm.rs:586:21
  26:     0x7f5e82fdbf71 - starcoin_vm_runtime::starcoin_vm::StarcoinVM::dry_run_transaction::h5f9d4db2adb57917
                               at /home/runner/work/starcoin/starcoin/vm/vm-runtime/src/starcoin_vm.rs:937:66
  27:     0x7f5e82d5eec4 - starcoin_transactional_test_harness::StarcoinTestAdapter::run_transaction::h6b5ff4528ee5bdc8
  28:     0x7f5e82d697cf - <starcoin_transactional_test_harness::StarcoinTestAdapter as move_transactional_test_runner::framework::MoveTestAdapter>::handle_subcommand::h1b98f32fd5a3232d
  29:     0x7f5e82d35ee0 - move_transactional_test_runner::framework::MoveTestAdapter::handle_command::h32c7b2b645444cb4
  30:     0x7f5e82d44f39 - move_transactional_test_runner::framework::run_test_impl::h9d756737cfb152fd
  31:     0x7f5e82c680e2 - core::ops::function::FnOnce::call_once::h9c8047eac0590519
  32:     0x7f5e82cfe778 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h048cbfc63673e73e
  33:     0x7f5e82d115ed - std::sys_common::backtrace::__rust_begin_short_backtrace::h9697b13d35b3d284
  34:     0x7f5e82cfe994 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb150dd6315db54b4
  35:     0x7f5e8403ca03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf70ac038171e3e1a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  36:     0x7f5e8403ca03 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he6690128792365ad
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  37:     0x7f5e8403ca03 - std::sys::unix::thread::Thread::new::thread_start::ha07928d93d5a5ec9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  38:     0x7f5e82196609 - start_thread
  39:     0x7f5e826b2103 - clone
  40:                0x0 - <unknown>
test integration-test::ascii_test.move ... FAILED

failures:
    integration-test::ascii_test.move

test result: FAILED. 1 passed; 1 failed; 0 filtered out
```

**Expected behavior:**

All test should be passed like on test network.

**Steps to reproduce:**

1. Change network to `barnard` in 
https://github.com/starcoinorg/starcoin-framework-commons/blob/b34fcdb9cc60103bd792057719d073ef5cc7aa9d/integration-tests/ascii_test.move#L1
2. Run `mpm integration-test`  

**Other information:**

mpm version:
```
$ mpm --version
move-package-manager 1.11.7-rc
```

**Comment by jolestar** [comment]
if set `-n barnard`, the integration test will execute the test after the Barnard genesis transaction. But Barnard genesis's move stdlib is very old, and can not execute the latest Move code.  

if you want to test a Move script base on Barnard's state, you can set the RPC argument, and Give a block number.

**Comment by 0xpause** [comment]
Got it, thanks.
